version: '3.8'

services:
  recommendation_app:
    build: .
    container_name: recommendation_system
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

networks:
  default:
    name: recommendation_network
